services:
  - displayName: Alertmanager
    port: 9093
    namespace: monitoring-prometheus
    name: alertmanager-operated
  - displayName: Prometheus
    port: 9090
    namespace: monitoring-prometheus
    name: prometheus-operated
  - displayName: Grafana
    port: 3000
    namespace: monitoring-prometheus
    name: prometheus-production-grafana
  - displayName: Kibana
    port: 5601
    namespace: monitoring-eck
    name: kibana-kb-http
  - displayName: Elasticsearch
    port: 9200
    namespace: monitoring-eck
    name: elasticsearch-es-http
