apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: multiforward
spec:
  version: v0.0.0
  homepage: https://github.com/njnygaard/kubectl-multiforward
  shortDescription: Port Forward to multiple Kubernetes Services
  description: |
    This plugin allows you to forward to multiple Kubernetes Services
    without the use of multiple terminal windows.
  caveats: |
    * You should have ~/.multiforward.yaml or ./.multiforward.yaml configured
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/njnygaard/kubectl-multiforward/releases/download/v0.0.0/kubectl-multiforward_v0.0.0_darwin_amd64.tar.gz
    sha256: c90dd260212b7da7163f12a27269923dedaeb17667616d990aa7ddbee31d2364
    bin: kubectl-multiforward
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/njnygaard/kubectl-multiforward/releases/download/v0.0.0/kubectl-multiforward_v0.0.0_linux_amd64.tar.gz
    sha256: 3253a981099abceb41f2ea32c89489fd1ba459d950becef2e302f79a8b2f0507
    bin: kubectl-multiforward
  # - selector:
  #     matchLabels:
  #       os: windows
  #       arch: amd64
  #   uri: https://github.com/njnygaard/kubectl-multiforward/releases/download/v0.0.0/kubectl-multiforward_v0.0.0_windows_amd64.tar.gz
  #   sha256: 8fe0fefe22816c3c34116f7b2e236bc351db053a839f7e2f396c7eaaf88e612c
  #   bin: kubectl-multiforward.exe
